name: "{{ name }}"
author: "{{ authorName }} <{{ authorEmail }}>"
description: "{{ description }}"

{% if inputs.length %}
inputs:
  {% for input in inputs %}
  {{ input.name }}:
    required: {{ input.required }}
    description: "{{ input.description }}"
    default: "{{ input.default }}"
  {% endfor %}
{% endif %}
{% if outputs.length %}
outputs:
  {% for output in outputs %}
  {{ output.name }}:
    description: "{{ output.description }}"
    {% if composite %}
    value: {% raw %}${{{% endraw %}steps.{{ output.name }}_setter.outputs.{{ output.name }}_value {%raw %}}}{% endraw %}
    {% endif  %}
  {% endfor %}
{% endif %}

runs:
  {% if not composite %}
  using: "node16"
  main: "dist/index.js"
  {% else %}
  using: composite
  steps:
    - name: Sanity check
      shell: bash
      run: echo 'Your action is running!'
  {% endif %}
